### ISSUE TITLE
where to put various small suggestions/patches?

### ISSUE THREAD

**Issue by crides** [betaveros/noulith#14]
Hi, I've been hacking noulith as I'm using it. These are mostly small patches here and there, and I wonder how do you want me or others to submit them? Should I open a PR for each of them? For me it seems a bit too much for each small thing, but I wanna know how you think about that

In any case, you can see them [in my fork](https://github.com/crides/noulith)

**Comment by betaveros** [comment]
Hi, feel free to make small PRs; I think it's easier to discuss that way.
