### ISSUE TITLE
Indexing precedence

### ISSUE THREAD

**Issue by max-sixty** [betaveros/noulith#9]
I'm not sure whether you're here to answer questions — no worries at all if you're not.

Does this fail because indexing is lower precedence than a function call?

```
X := [1,2,3];

print X[0];

# ERROR: type error: Chain cannot use nonblock in operator position: [1, 2, 3]
# print X[0];

#    at op 1/1 (14:7-8)
#    at ;-sequence(2/4) (12:13-18:9)
```

But this seems to work:

```
X[0].print;
```

**Comment by betaveros** [comment]
Hi! The problem is that `print X[0]` parses as calling the binary operator `X` on the operands `print` and `[0]`, much like `1 .+ [0]`. Generally, mere juxtaposition for calling a function with one operand is finicky. I'll think about how to make the error message better.

**Comment by max-sixty** [comment]
That makes sense, thanks

**Comment by tom-huntington** [comment]
@max-sixty The best way to this is
```
print! X[0];
```

> ! is syntax that's spiritually sort of like what Haskell's $ lets you write. It's as tight as an opening parenthesis on its left, but performs a function call that lets you can omit the closing one up to the next semicolon or so. f! a, b is f(a, b).
